### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by wangjie07070910** [YuboZhangPKU/ERICA#8]
非常感谢提供这个工具，遇到以下错误，尝试解决未果。
(ERICA) jw@hpc10:/netscratch/software/ERICA$ python /netscratch/software/ERICA/ERICAPrediction.py -i Neo/five_pop_Scaffold_35827.txt -o Neo/five_pop_10_res.txt -p 5

Sun Jun 23 09:53:57 2024        Neo/five_pop_Scaffold_35827.txt        Data Preprocessing > > > > > > > > > >

Process Process-1:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/netscratch/conda/anaconda3/envs/ERICA/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/netscratch/conda/anaconda3/envs/ERICA/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/netscratch/software/ERICA/ERICAPrediction.py", line 129, in FiveTaxonDataPrediction
    data = FiveTaxonDataProcess(MSA)
  File "/netscratch/software/ERICA/ERICAPrediction.py", line 93, in FiveTaxonDataProcess
    lines = np.array([list(x) for x in lines], dtype=np.uint8)
ValueError: setting an array element with a sequence.

**Comment by YuboZhangPKU** [comment]
您好，感谢您的使用。您可以考虑首先运行测试数据集。如果测试数据集能够正确运行，该错误可能是由于数据格式存在问题造成的。
目前5类群模型的输入格式为40行序列比对结果，其中每行为一条序列，每8行代表一个类群。除序列外，文件内不需要有其他内容。序列内容支持ATCGN-及对应小写字符。请您再检查一下文件格式是否存在问题。

**Comment by wangjie07070910** [comment]
感谢回复。事例数据我可以正常运行并得到结果。我的第二步输入使用的是第一步的vcf2MSA得到的结果，由于第一步正常产生了输出文件，没有报错。下面是我的完整代码。  #! /bin/bash

# five-taxon model
python vcf2MSA.py \
-i Annotaton_biallelic.vcf.gz \
-r neo.fa \
-o Neo/five_pop \
-f diplo \
--include Scaffold_35827 \
-P1 Nfulvus_16561 \
-P2 Npictus_117894 \
-P3 Nwilsmorei_135608 \
-P4 Nsutor_12604 \
-P5 Npelobatoides_135600
(上面代码可以产生five_pop_Scaffold_35827.txt文件，没有提示错误)

python ERICAPrediction.py -i Neo/five_pop_Scaffold_35827.txt -o Neo/five_pop_10_res.txt -p 5

python ERICAVisualization.py \
-i Neo/five_pop_10_res.txt \
-o Neo/five_pop_10_10k \
-p 5 \
-w 10000 \
-r 1:200 \
-c Scaffold_35827 \
-d 0.5

**Comment by YuboZhangPKU** [comment]
您好，能否请您再查看一下文件行数或文件大小？或者如果您方便的话，也可以将该文件或其中的部分内容提供给我。

**Comment by wangjie07070910** [comment]
请问您的邮箱是多少？如果方便的话，我使用邮箱发给您。您需要这个five_pop_Scaffold_35827.txt文件的subset对吧？

**Comment by YuboZhangPKU** [comment]
嗯嗯，是的，您可以将文件发送至yubozhang@pku.edu.cn。
